import '../units/unit_registry.dart';

/// Shared catalog for built-in constants, functions, and reserved identifiers.
class BuiltInSymbolCatalog {
  BuiltInSymbolCatalog._();

  static const Set<String> constantNames = <String>{'pi', 'e', 'i'};

  static const Set<String> functionNames = <String>{
    'data',
    'dataset',
    'ds',
    'vec',
    'vector',
    'mat',
    'matrix',
    'identity',
    'eye',
    'zeros',
    'ones',
    'diag',
    'to',
    'convert',
    'dot',
    'cross',
    'norm',
    'mag',
    'unit',
    'transpose',
    'tr',
    'det',
    'inv',
    'trace',
    'count',
    'sum',
    'product',
    'mean',
    'avg',
    'median',
    'mode',
    'range',
    'varp',
    'variancep',
    'vars',
    'variances',
    'variance',
    'stdp',
    'stdevp',
    'stds',
    'stdevs',
    'stddev',
    'mad',
    'meanabsdev',
    'quantile',
    'percentile',
    'quartiles',
    'iqr',
    'wmean',
    'weightedmean',
    'factorial',
    'fact',
    'ncr',
    'comb',
    'choose',
    'npr',
    'perm',
    'binompmf',
    'binomialpmf',
    'binomcdf',
    'binomialcdf',
    'poissonpmf',
    'poissoncdf',
    'geompmf',
    'geomcdf',
    'normalpdf',
    'normpdf',
    'normalcdf',
    'normcdf',
    'zscore',
    'uniformpdf',
    'uniformcdf',
    'covp',
    'covs',
    'corr',
    'correlation',
    'linreg',
    'linearregression',
    'linpred',
    'sin',
    'cos',
    'tan',
    'asin',
    'acos',
    'atan',
    'sqrt',
    'abs',
    'conj',
    're',
    'im',
    'arg',
    'polar',
    'cis',
    'ln',
    'log',
    'log10',
    'log2',
    'exp',
    'pow',
    'min',
    'max',
    'floor',
    'ceil',
    'round',
    'simplify',
    'expand',
    'factor',
    'solvesystem',
    'linsolve',
    'fn',
    'function',
    'eq',
    'solve',
    'nsolve',
    'diff',
    'derivative',
    'derivativeat',
    'integral',
    'integrate',
    'plot',
    'evalat',
    'root',
    'roots',
    'intersect',
    'intersections',
    'slope',
    'area',
  };

  static bool isBuiltInConstant(String name) {
    return constantNames.contains(name.toLowerCase());
  }

  static bool isBuiltInFunction(String name) {
    return functionNames.contains(name.toLowerCase());
  }

  static bool isUnitIdentifier(String name) {
    return UnitRegistry.instance.lookup(name) != null;
  }

  static bool isReservedSymbol(String name) {
    return isBuiltInConstant(name) ||
        isBuiltInFunction(name) ||
        isUnitIdentifier(name);
  }
}
